language: python
python:
  - "3.5"

before_install:
  - sudo apt-get -qq expect

install:
  - "pip install -r requirements.txt"
  - "python setup.py install"

script:
  - expect -c 'spawn gitroom; expect \"CHOICE:\"; send "9"; send "\r"'