language: python
python:
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"
  # - "pypy3"

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - "./tests/test.sh"

notifications:
  email:
    recipients:
      - btskinner@coe.ufl.edu
    on_success: change
    on_failure: change

deploy:
  - provider: pypi
    user: btskinner
    password:
      secure: "BB8RSn6OSMHPqzeTFzMZmoAtVFzvaEbYDTw/t+er6j2UDZNMdAFljFCrO5bwpRKRBqQG646v+Y7SO2ZVGKPhP+xUl2zwFCl3wT95IPtCrDBhPKjuOF9p/xJ96hnzjjQ1r4ZA6VMhXlgSf1CMLwlBgebFIaHGruSsTkEtCjkYNTxncc97+fAmX7g0p6F0zytL7yyz8ULPa5EEgyQcmU3F7xC2RRbMk56k6cqESjz5bcEZpqFIbTIjyG/J6dlSior2gX80mrEqY+PSh+0PbA5bYpoH2Fjs7CzsIQGiSQJ+ANBWyiYG0rdvORc1Nrm8O242UW4bupKUwoCdPSsActVjyH7VHf5+xootuZhF9gHi+IKITSjf1Q0w3JODnFSUq73GBhHnCpY+7IvVqidWK+8dLNfYbbJo96gb4DtikzKFKSfufT0Ffi7RD3cFVgnmTd7fCvbJ1ybIbMRjEPSuEV0NjCSgU+6c1WdUkwILFbV2sYPcEYR5raF0jxsh8jCeDSv2v2ZOJw4esGbfHsSR6zTfAuXWrzIQ2oUTeCrCLKxF+TqqPVock0XvegLItEDgfBNCFHkjuc/m5YRoDkPvckFC0XIvVcU+zQFNshwtZ1Ny5cwcvhObsR/IrtyV3EGILGX3+u+B3keE3I362+GVYOZebLST6q9mLHn1ZAqrwYovL8k="
    on:
      tags: true
