language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
install:
- pip install -r requirements.txt
- python setup.py install
script:
- "./tests/test.sh"
notifications:
  email:
    recipients:
    - btskinner@coe.ufl.edu
    on_success: change
    on_failure: change
deploy:
- provider: pypi
  user: btskinner
  password:
    secure: VUUw/IbGc3MmNdlKhkMrF5JE6AtMcY4CYKvGLAZ8MJUEGqpi7i5Fh69Euldm5J423nKkyIXXZGHP60O4o2mz0PtjHR/EtAi89ITipMQ8T/OeIaPCru3akuhWrS8PoFKgquVviCnHYi5uG6VT2gIi60g3AkuA9j3rFzonsF8gdEPN0quJhVij9WNUB81BOSTvDoP53CNLpIQeTU5bFeAqjPsbQSv0gTj4jeg/7lndPDrXs434bf+tJ4JS+HlJ4ggL4VWMGG0etzqVyZu+JJu1Io0vB3QS+Y16T9dleUYIhAxra1RQVy/ku5F9NOuHtGtC0y7gd21SFZC4Lmj302+8C+OLPiA+wf7hdpWO5uCEvBrtfydfrsM0vkQ0QO644FPqgRgcwj/Ezo0QO9zkaRdS7KkoJgI1K+3m5a1vZwbzmu9Vinw/K9EgAUW2GJnyOdehQulxbMAHRStAZRWqDkGftAnUE22xCIVz/gArLxHen2SVML+DCxiCsQC/VemnH5VaH3n7L1MZ0FRf6XpBpnahX5Xu1LZVRcKfvgXWMOhkn5W/Qx76Zr1x9nr1CscfUdhDB2mPgD1egC7KU4ZDwDKk5JD1tDfDFIK5ATWCdg1q+JE/8pkGCfbO1j83YqpM0ke5mS+L9pdH0EMvH6p8u3BZy8samYyYDWG0sLLb7mIu1ic=
  on:
    tags: true
    
