title:            grm
tagline:          'Python package'
description:      'GitRoom Manager: A command line GitHub classroom manager'
github:		  https://github.com/btskinner/grm
version:	  0.2.0
url:		  http://btskinner.me
baseurl: 	  "/grm"

highlighter:      rouge
permalink:        pretty


