title:            grm
tagline:          'Python package'
description:      'GitRoom Manager: A command line GitHub classroom manager'
github:		  https://github.com/btskinner/grm
version:	  0.4.1
url:		  https://btskinner.io
baseurl: 	  "/grm"

highlighter:      rouge
permalink:        pretty


