__version__ = '0.4.0'
__ws = 'https://btskinner.io/'
__gh = 'https://github.com/btskinner/'
__nm = 'grm'
__dc = '{}{}'.format(__ws, __nm)
__rp = '{}{}'.format(__gh, __nm)
__dl = '{}{}/archive/{}-v{}.tar.gz'.format(__gh, __nm, __nm, __version__)
__au = 'Benjamin Skinner'
__em = 'btskinner@coe.ufl.edu'
